# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: security.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0esecurity.proto\x12\x07mapr.fs\"\xac\x02\n\x0e\x43redentialsMsg\x12\x0b\n\x03uid\x18\x01 \x01(\r\x12\x0c\n\x04gids\x18\x02 \x03(\r\x12\x0e\n\x06isRoot\x18\x03 \x01(\x08\x12\x10\n\x08userName\x18\x04 \x01(\t\x12\x10\n\x08\x63lientIp\x18\x05 \x01(\r\x12\x1b\n\x13isPrivilegedProcess\x18\x06 \x01(\x08\x12\x1e\n\x16logInSeperateAuditPath\x18\x07 \x01(\x08\x12\x11\n\ttenantUid\x18\x08 \x01(\r\x12\x12\n\ntenantGids\x18\t \x03(\r\x12!\n\x19\x65ncryptedImpersonationMsg\x18\n \x01(\x0c\x12\x17\n\x0f\x66romMastGateway\x18\x0b \x01(\x08\x12+\n\x0c\x63\x61pabilities\x18\x0c \x01(\x0b\x32\x15.mapr.fs.Capabilities\"&\n\x0c\x43\x61pabilities\x12\x16\n\x0e\x63lusterOpsMask\x18\x01 \x01(\x04\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\x0c\"\x95\x03\n\x0cTicketAndKey\x12\x17\n\x0f\x65ncryptedTicket\x18\x01 \x01(\x0c\x12\x1d\n\x07userKey\x18\x02 \x01(\x0b\x32\x0c.mapr.fs.Key\x12*\n\tuserCreds\x18\x03 \x01(\x0b\x32\x17.mapr.fs.CredentialsMsg\x12\x12\n\nexpiryTime\x18\x04 \x01(\x04\x12\x17\n\x0f\x63reationTimeSec\x18\x05 \x01(\x04\x12\x1d\n\x15maxRenewalDurationSec\x18\x06 \x01(\x04\x12\x1a\n\x12\x63\x61nUserImpersonate\x18\x07 \x01(\x08\x12\x0b\n\x03ips\x18\x08 \x03(\x05\x12\x18\n\x10impersonatedUids\x18\t \x03(\x05\x12\x18\n\x10impersonatedGids\x18\n \x03(\x05\x12\x10\n\x08isTenant\x18\x0b \x01(\x08\x12\x12\n\nisExternal\x18\x0c \x01(\x08\x12\x17\n\x0flastRenewalTime\x18\r \x01(\x04\x12\x1d\n\x15\x63\x61nUserGenerateTicket\x18\x0e \x01(\x08\x12\x1a\n\x12isRemoteTempTicket\x18\x0f \x01(\x08\x42\x37\n\x11\x63om.mapr.fs.protoH\x03Z ezmeral.hpe.com/datafab/fs/proto')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'security_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\021com.mapr.fs.protoH\003Z ezmeral.hpe.com/datafab/fs/proto'
  _globals['_CREDENTIALSMSG']._serialized_start=28
  _globals['_CREDENTIALSMSG']._serialized_end=328
  _globals['_CAPABILITIES']._serialized_start=330
  _globals['_CAPABILITIES']._serialized_end=368
  _globals['_KEY']._serialized_start=370
  _globals['_KEY']._serialized_end=388
  _globals['_TICKETANDKEY']._serialized_start=391
  _globals['_TICKETANDKEY']._serialized_end=796
# @@protoc_insertion_point(module_scope)
